import { CitySuggestion } from "./types";

// A curated list of popular travel destinations for instant autocomplete
export const POPULAR_DESTINATIONS: CitySuggestion[] = [
  { name: "Paris", country: "France" },
  { name: "London", country: "United Kingdom" },
  { name: "New York City", country: "USA" },
  { name: "Tokyo", country: "Japan" },
  { name: "Rome", country: "Italy" },
  { name: "Barcelona", country: "Spain" },
  { name: "Dubai", country: "UAE" },
  { name: "Singapore", country: "Singapore" },
  { name: "Amsterdam", country: "Netherlands" },
  { name: "Bangkok", country: "Thailand" },
  { name: "Bali", country: "Indonesia" },
  { name: "Istanbul", country: "Turkey" },
  { name: "Sydney", country: "Australia" },
  { name: "Kyoto", country: "Japan" },
  { name: "Machu Picchu", country: "Peru" },
  { name: "Santorini", country: "Greece" },
  { name: "Cairo", country: "Egypt" },
  { name: "Rio de Janeiro", country: "Brazil" },
  { name: "Cape Town", country: "South Africa" },
  { name: "Reykjavik", country: "Iceland" },
  { name: "Venice", country: "Italy" },
  { name: "Prague", country: "Czech Republic" },
  { name: "Seoul", country: "South Korea" },
  { name: "Lisbon", country: "Portugal" },
  { name: "Maui", country: "Hawaii, USA" },
  { name: "Bora Bora", country: "French Polynesia" },
  { name: "Marrakech", country: "Morocco" },
  { name: "Vancouver", country: "Canada" },
  { name: "Queenstown", country: "New Zealand" },
  { name: "Petra", country: "Jordan" },
  { name: "Hong Kong", country: "China" },
  { name: "Budapest", country: "Hungary" },
  { name: "Dubrovnik", country: "Croatia" },
  { name: "Edinburgh", country: "Scotland" },
  { name: "Florence", country: "Italy" },
  { name: "Havana", country: "Cuba" },
  { name: "Cusco", country: "Peru" },
  { name: "Kathmandu", country: "Nepal" },
  { name: "Las Vegas", country: "USA" },
  { name: "Los Angeles", country: "USA" },
  { name: "Miami", country: "USA" },
  { name: "San Francisco", country: "USA" },
  { name: "Mexico City", country: "Mexico" },
  { name: "Cancun", country: "Mexico" },
  { name: "Toronto", country: "Canada" },
  { name: "Mumbai", country: "India" },
  { name: "New Delhi", country: "India" },
  { name: "Jaipur", country: "India" },
  { name: "Goa", country: "India" },
  { name: "Maldives", country: "Maldives" },
  { name: "Phuket", country: "Thailand" },
  { name: "Chiang Mai", country: "Thailand" },
  { name: "Hanoi", country: "Vietnam" },
  { name: "Ho Chi Minh City", country: "Vietnam" },
  { name: "Kuala Lumpur", country: "Malaysia" },
  { name: "Berlin", country: "Germany" },
  { name: "Munich", country: "Germany" },
  { name: "Vienna", country: "Austria" },
  { name: "Zurich", country: "Switzerland" },
  { name: "Geneva", country: "Switzerland" },
  { name: "Stockholm", country: "Sweden" },
  { name: "Copenhagen", country: "Denmark" },
  { name: "Oslo", country: "Norway" },
  { name: "Helsinki", country: "Finland" },
  { name: "Athens", country: "Greece" },
  { name: "Mykonos", country: "Greece" },
  { name: "Dublin", country: "Ireland" },
  { name: "Brussels", country: "Belgium" },
  { name: "Madrid", country: "Spain" },
  { name: "Seville", country: "Spain" },
  { name: "Honolulu", country: "USA" },
  { name: "Banff", country: "Canada" },
  { name: "Whistler", country: "Canada" },
  { name: "Nice", country: "France" },
];

export const LOADING_TIPS = [
  "Roll your clothes instead of folding them to save space and prevent wrinkles.",
  "Always email yourself a copy of your passport and important documents.",
  "Download offline maps before you arrive at your destination.",
  "Pack a portable charger; you'll take more photos than you think!",
  "Learn 'Hello' and 'Thank You' in the local language.",
  "Notify your bank about your travel dates to avoid blocked cards.",
  "Bring a reusable water bottle to save money and the environment.",
  "Pack a small first-aid kit with essentials like band-aids and painkillers.",
  "Wake up early to see popular attractions without the crowds.",
  "Don't be afraid to try local street food – follow the locals!",
  "Pack a change of clothes in your carry-on in case of lost luggage.",
  "Use packing cubes to stay organized.",
  "Ask locals for restaurant recommendations, not just the hotel concierge.",
  "Take photos of your luggage before checking it in.",
  "Carry a pen for filling out customs forms on the plane.",
  "Bring earplugs and an eye mask for better sleep during transit.",
  "Check the visa requirements well in advance.",
  "Keep your hotel address in the local language handy.",
  "Dress in layers to adapt to changing weather conditions.",
  "Respect local customs and dress codes, especially in religious sites."
];
